# Imagen base con .NET SDK para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Instalar dependencias nativas necesarias para SkiaSharp
RUN apt-get update && apt-get install -y \
    libfontconfig1 \
    libfreetype6 \
    libpng16-16 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

# Copia todo y restaura dependencias
COPY . .
RUN dotnet restore "./Overtime_Project_Backend.csproj"
RUN dotnet publish "./Overtime_Project_Backend.csproj" -c Release -o /app/publish /p:TreatWarningsAsErrors=false

# Imagen final con solo el runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

# Instalar también las dependencias nativas en el runtime
RUN apt-get update && apt-get install -y \
    libfontconfig1 \
    libfreetype6 \
    libpng16-16 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Overtime_Project_Backend.dll"]
